Imported Debian version 1.17.5ubuntu5.5

diff --git a/dselect/methods/multicd/install b/dselect/methods/multicd/install
--- a/dselect/methods/multicd/install
+++ b/dselect/methods/multicd/install
@@ -13,7 +13,7 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 set -e
 vardir="$1"
@@ -53,7 +53,7 @@ xit=1
 do_umount() {
 	if [ "$method" = "multi_mount" ]
 	then
-		echo /bin/true
+		echo true
 		return
 	fi
 	if [ -n "$umount" ]; then
@@ -66,7 +66,7 @@ do_mount() {
 
 	if [ "$method" = "multi_mount" ]
 	then
-		echo /bin/true
+		echo true
 		return
 	fi
 
@@ -110,7 +110,7 @@ do
 
 	perl -e '
 		($binaryprefix,$predep,$thisdisk) = @ARGV;
-		open(P,"< $predep") || die "cannot open $predep: $!\n";
+		open(P, "< $predep") or die "cannot open $predep: $!\n";
 		while (<P>) {
 			s/\s*\n$//;
 			$package= $_ if s/^Package: //i;
@@ -118,10 +118,11 @@ do
 			@filename= split(/ /,$_) if s/^Filename: //i;
 			@msdosfilename= split(/ /,$_) if s/^MSDOS-Filename: //i;
 		}
-		length($package) || die "internal error - no package";
-		@filename || die "internal error - no filename";
-		@filename==@msdosfilename || !@filename || !@msdosfilename ||
-			die "internal error - mismatch >@filename< >@msdosfilename<";
+		die "internal error - no package" if length($package) == 0;
+		die "internal error - no filename" if not @filename;
+		die "internal error - mismatch >@filename< >@msdosfilename<"
+			if @filename && @msdosfilename &&
+			   @filename != @msdosfilename;
 		if ($medium && ($medium ne $thisdisk)) {
 			print "
 
@@ -147,8 +148,10 @@ Please change the discs and press <RETURN>.
 			} else {
 				$base= $filename[$i]; $base =~ s,.*/,,;
 				$msdosbase= $msdosfilename[$i]; $msdosbase =~ s,.*/,,;
-				defined($c= open(X,"-|")) ||
+				$c = open(X, "-|"));
+				if (not defined $c) {
 					die "failed to fork for find: $!\n";
+				}
 				if (!$c) {
 					exec("find", "-L",
 					     length($binaryprefix) ? $binaryprefix : ".",
@@ -163,7 +166,7 @@ Please change the discs and press <RETURN>.
 				}
 			}
 			if (!length($invoke)) {
-				print STDERR "
+				warn "
 
 Oh dear, I need to install or upgrade $package, but I don'\''t see
 the appropriate file(s) anywhere.  I'\''m expecting version $version or
@@ -196,7 +199,7 @@ done
 	my $STATUS = "$vardir/status";
 	my %Installed, %Filename, %Medium;
 	print "Get currently installed package versions...";
-	open(IN, "$STATUS") or die "Cannot open $STATUS: $!\n";
+	open(IN, "$STATUS") or die "cannot open $STATUS: $!\n";
 	$line = 0;
 	{ local $/ = "";
 	while (<IN>) {
@@ -263,7 +266,8 @@ done
 			print "Please change the discs and press <RETURN>\n";
 			system($umount);
 			<STDIN>;
-			system($mount); $? and warn("Cannot mount $mount\n");
+			system($mount);
+			$? and warn("cannot mount $mount\n");
 		} continue {
 			if (-r "$mountpoint/.disk/info") {
 			    open(IN, "$mountpoint/.disk/info") or die("$mountpoint/.disk/info: $!\n");
@@ -282,7 +286,7 @@ done
 			symlink "$mountpoint/$hierbase/$Filename{$_}",
 				"tmp/$basename";
 		}
-		chdir "tmp" or die "Cannot chdir to tmp: $!\n";
+		chdir "tmp" or die "cannot chdir to tmp: $!\n";
 		system "dpkg", "-iGROEB", ".";
 		unlink <*>;
 		chdir "..";
@@ -305,5 +309,3 @@ echo -n 'Installation OK.  Hit RETURN.  '
 read response
 
 xit=0
-
-# vim:ts=4:sw=4:aw:ai:
